# GitHub Pages Configuration for CIN Framework
# This configuration ensures the website is served from .github/web directory

# Site settings
title: "CIN Framework"
description: "CIN FRAMEWORK – WEB 4 – POWERED BY LOCAL SELF-SUFFICIENCY AND AGGRESSIVE SECURITY"
url: "https://cin-framework.github.io"
baseurl: "/cin-framework"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .github/workflows/
  - cin-cli/
  - cin-framework/
  - cin-library/
  - .1.NO_EDITE_NO_DELETE/

# Include files that start with underscore
include:
  - _config.yml

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# SEO settings
author: "Ayoub Alarjani (Mawi Man)"
company: "CIN FRAMEWORK"
location: "Morocco"

# Social links
social:
  github: "https://github.com/cin-framework"
  website: "https://www.cin-framework.com"
  developer: "https://www.mawiman.com"

# Contact information
email:
  support: "support@cin-framework.com"
  contact: "contact@cin-framework.com"
  admin: "admin@cin-framework.com"
  dev: "dev@cin-framework.com"
  mawi: "mawi@cin-framework.com"